### ISSUE TITLE
Error importing skbio OrdinationResults

### ISSUE THREAD

**Issue by HannesHolste** [biocore/mds-approximations#19]
@wasade or @ElDeveloper any idea why this is happening? 

my virtual conda env is running skbio v0.4.0, but oddly, this statement causes an error:
`from skbio import OrdinationResults`

I even tried `from skbio.stats.ordination import OrdinationResults` with no success. Nothing on Google, either. And skbio/**init**.py looks fine to me:

```
from skbio._base import OrdinationResults


__all__ = ['Sequence', 'DNA', 'RNA', 'Protein', 'GeneticCode',
           'DistanceMatrix', 'local_pairwise_align_ssw', 'TabularMSA',
           'TreeNode', 'nj', 'read', 'write', 'OrdinationResults']
```

Error:

```
$ nosetests
.....................E
======================================================================
ERROR: Failure: ImportError (cannot import name OrdinationResults)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/hannes/miniconda2/envs/mdsapprox/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/hannes/miniconda2/envs/mdsapprox/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/hannes/miniconda2/envs/mdsapprox/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/hannes/bio/knightlab/mds-approximations/mdsa/tests/test_ssvd.py", line 4, in <module>
    from skbio import OrdinationResults
ImportError: cannot import name OrdinationResults

----------------------------------------------------------------------
Ran 22 tests in 1.844s

FAILED (errors=1)s
```

Offending code:

``` python
import unittest

from skbio import DistanceMatrix
from skbio import OrdinationResults
from skbio.util import assert_ordination_results_equal
from skbio.util import get_data_path

from mdsa.algorithms.ssvd import Ssvd


class TestSsvd(unittest.TestCase):
    def setUp(self):
        self.test_matrix = DistanceMatrix.read(
            get_data_path('unweighted_unifrac_dm.txt'), format='lsmat')
        self.reference_results = OrdinationResults.read(
            get_data_path('unweighted_unifrac_pc.txt'))
        self.ssvd = Ssvd()

    def test_ssvd(self):
        eigenvectors, eigenvalues, percentages = self.ssvd.run(
            self.test_matrix)
        ssvd_results = OrdinationResults(eigvals=eigenvalues,
                                         site=eigenvectors,
                                         proportion_explained=percentages)

        assert_ordination_results_equal(ssvd_results,
                                        self.reference_results)
```

**Comment by ElDeveloper** [comment]
Seems like the move from `skbio.stats.ordination` to `skbio` happened
somewhere in-between 0.4.0 and 0.4.2. You are right, in 0.4.0 `from
skbio import OrdinationResults` will fail, seems like you have to do:
`from skbio.stats.ordination import OrdinationResults` instead. Now that
I recall, when we tried this in my computer, I was using 0.4.2, sorry
for the confusion.

**Comment by HannesHolste** [comment]
@ElDeveloper aha, thanks, you're right. Oddly enough, PyCharm was complaining but that import threw no runtime error.

@antgonza can I set the minimum version of mdsa project to use the latest skbio 0.4.2 in a separate PR?

**Comment by antgonza** [comment]
@HannesHolste 0.4.2 sounds perfect. Thanks!
